name: "🐞 - Bug Report"
title: "🐞 - "
description: Report a bug
labels: ["bug", "state: need triage"]

body:
  - type: input
    id: playground-link
    attributes:
      label: Code Example URL
      description: |
        Link a CodeSandbox, Stackblitz, GitHub repository, or similar to help us reproduce the issue faster, [try reproduce in our online playground](https://taiga-ui.dev/stackblitz).
      placeholder: https://stackblitz.com/edit/angular-...

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Add any other context about the problem here, such as screenshots or videos.
    validations:
      required: true

  - type: input
    id: taiga-version
    attributes:
      label: Taiga UI version
      placeholder: x.y.z
    validations:
      required: true

  - type: dropdown
    id: browser-specific
    attributes:
      label: Browser Used
      description: Select the browser where the bug was observed.
      options:
        - label: Chrome
        - label: Firefox
        - label: Safari
        - label: Edge

  - type: dropdown
    id: operating-systems
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one.
      options:
        - label: macOS
        - label: Windows
        - label: Linux
        - label: iOS
        - label: Android
