name: '🐞 - Bug Report'
title: '🐞 - '
description: Report a bug
labels: ['bug', 'state: need triage']

body:
  - type: input
    id: playground-link
    attributes:
      label: Playground Link
      description: |
        Link to an isolated reproduction [in our online playground](https://taiga-ui.dev/stackblitz).

        If either of the following holds true:
        - You can't reproduce the issue in the playground
        - Your issue requires some complex setup - such as multiple files or a specific folder structure.

        So you can use any link that might help for reproduction bug: github repo, demo url, etc.

        ***Help us to help you!***
      placeholder: https://stackblitz.com/edit/angular-...

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Please provide the exception or error you saw.
        How do you trigger this bug?
        Please walk us through it step by step.
        Please provide a screenshot if possible.
    validations:
      required: true

  - type: input
    id: angular-version
    attributes:
      label: Angular version
      placeholder: x.y.z

  - type: input
    id: taiga-version
    attributes:
      label: Taiga UI version
      placeholder: x.y.z

  - type: checkboxes
    id: browser-specific
    attributes:
      label: Which browsers have you used?
      description: You may select more than one.
      options:
        - label: Chrome
        - label: Firefox
        - label: Safari
        - label: Edge

  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one.
      options:
        - label: macOS
        - label: Windows
        - label: Linux
        - label: iOS
        - label: Android
