name: "🐞 - Bug Report"
title: "🐞 - "
description: Report a bug
labels: ["bug", "state: need triage"]

body:
  - type: input
    id: playground-link
    attributes:
      label: Reproduction url
      description: |
        Link a Stackblitz, [try reproduce in our online playground](https://stackblitz.com/~/github.com/taiga-family/taiga-playground).
      placeholder: https://stackblitz.com/edit/angular-...
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Add any other context about the problem here, such as screenshots or videos.
    validations:
      required: true

  - type: input
    id: taiga-version
    attributes:
      label: Taiga UI version
      placeholder: x.y.z
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser Used
      description: Select the browser where the bug was observed.
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: dropdown
    id: operating-systems
    attributes:
      label: OS Used
      description: Select the OS where the bug was observed.
      options:
        - macOS
        - Windows
        - Linux
        - iOS
        - Android
    validations:
      required: true
