name: '🚀 - Feature Request'
title: '🚀 - '
description: Suggest a feature
labels: ['feature', 'state: need triage']

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Proposed solution.
        Alternatives considered.
    validations:
      required: true
