name: "🗂 - Task Request"
title: "🗂 - "
description: Suggest an enhancement
labels: ["state: need triage"]
type: Task

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Provide any additional details here as needed.
    validations:
      required: true
