name: 🤖 Auto sync labels
on:
  push:
    branches: [main]
    paths:
      - .github/labels.yml
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: micnncim/action-label-syncer@v1.3.0
        with:
          manifest: .github/labels.yml
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          prune: false
          repository: |
            taiga-family/.github
            taiga-family/linters
