name: 🤖 Auto sync labels
on:
  push:
    branches: [main]
    paths:
      - .github/labels.yml
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: micnncim/action-label-syncer@v1.3.0
        with:
          manifest: .github/labels.yml
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          prune: false
          repository: |
            taiga-family/.github
            taiga-family/linters
            taiga-family/ng-web-apis
            taiga-family/maskito
            taiga-family/ng-polymorpheus
            taiga-family/ng-morph
            taiga-family/ng-dompurify
            taiga-family/ng-event-plugins
            taiga-family/ng-event-plugins
            taiga-family/angular-contenteditable-accessor
            taiga-family/tui-editor
            taiga-family/renovate-config
            taiga-family/ci
            taiga-family/argus
