name: ⚙️ Lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
      - uses: taiga-family/ci/actions/setup/variables@v1.167.0
      - uses: taiga-family/ci/actions/setup/node@v1.167.0
      - run: npm run prettier -- --check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
